version: '3.8'

services:
  go-app:
    build: ./backend/kmkglass
    ports:
      - "8080:8080"
      - "6060:6060"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123437
      - DB_NAME=kmkglass
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123437
      MYSQL_DATABASE: kmkglass
    volumes:
      - ./backend/MySQLDB:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123437123437
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: